language: node_js
node_js:
  - "7"
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm@5

install:
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - gulp imagemin && gulp sass && gulp html && gulp jshint && gulp jsconcat-js && gulpmove-fonts

deploy:
  provider: pages
  skip_Cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/
  target_branch: master
  on:
    branch: master
